### ISSUE TITLE
Update the readme to contain dev environment build steps

### ISSUE THREAD

**Issue by danieltj27** [Forum-Promotion/help-center#9]
I've personally not used yarn before and I'm a bit of a novice when it comes to npm so getting the help centre build set up locally is a bit of a problem for me. I can see the readme file hasn't changed since the first commit.

Perhaps some thorough steps on how to get the system setup and usable would be helpful to ensure new contributors (like myself) can get set up and hopefully lend a hand in an easier way would be beneficial?

I'm keen to help, but I don't want to fudge the setup process and cause errors and headaches! 🙂

**Comment by malcolmjr96** [comment]
Hey Daniel, 

Thanks for helping out. Could you fill out this form: https://forms.gle/jS2nzQXpjuN7yEu5A

Once that is done, I'll add you to the repo.

**Comment by danieltj27** [comment]
No problem. I don't need adding to the repo, I'm happy to submit PRs as and when necessary but thanks for reaching out.
